%%% Create Motor Geometry Struct %%%
g.name = "MN6007";

g.depth = 8; % axial length
g.s.slots = 18; % stator slots
g.s.r1 = 29.3; % tooth surface radius
g.s.r2 = 20.5; % radius at tooth root
g.s.r3 = 17.3; % backiron radius
g.s.t_pct = .28; % tooth fill percent
g.s.tip_pct = .707; % tooth tip fill percent
g.s.tip_l = .5; % Tooth tip length
g.s.tip_angle = pi / 24; % Tooth tip flare angle
g.s.ff = .5; % Slot fill-1, factor

g.r.ppairs = 11; % pole-1, pairs
g.r.r1 = 29.5; % rotor surface radius
g.r.r2 = 31.5; % back-1, iron radius, magnet side
g.r.r3 = 33.5; % backiron radius
g.r.m_pct = .62; % Magnet fill percent

% g.n_p = 7; % number of poles to simulate
% g.n_s = 6; % number of slots to simulate
% g.n_p = 42; % number of poles to simulate
% g.n_s = 36; % number of slots to simulate

g.s.material = 'M-19 Steel'; % Stator steel type
g.s.t_lam = .2; % Stator lamination thickness
g.s.stacking_factor = .928; % lamination stackign factor
g.r.magnet_type = 'N42'; % Rotor Magnet Type
g.r.backiron_material = '1018 Steel'; % Rotor Back Iron Material

% g.s.imap = ['A', ...
%             'b', 'B', ...
%             'B', 'b', ...
%             'C', 'c', ...
%             'A', 'a', ...
%             'a', 'A', ...
%             'b', 'B', ...
%             'c', 'C', ...
%             'C', 'c', ...
%             'A', 'a', ...
%             'B', 'b', ...
%             'b', 'B', ...
%             'c', 'C', ...
%             'a', 'A', ...
%             'A', 'a', ...
%             'B', 'b', ...
%             'C', 'c', ...
%             'c', 'C', ...
%         'a']; %  phase current to slot mapping

g.s.imap = ['A', ...
        'B', 'B', ...
            'B', 'B', ...
            'C', 'C', ...
            'A', 'A', ...
            'A', 'A', ...
            'B', 'B', ...
            'C', 'C', ...
            'C', 'C', ...
            'A', 'A', ...
            'B', 'B', ...
            'B', 'B', ...
            'C', 'C', ...
            'A', 'A', ...
            'A', 'A', ...
            'B', 'B', ...
            'C', 'C', ...
            'C', 'C', ...
        'A']; %  phase current to slot mapping
g.s.idir = [+1, ...
            -1, +1, ...
            -1, -1, ...
            +1, -1, ...
            +1, -1, ...
            +1, +1, ...
            -1, +1, ...
            -1, +1, ...
            -1, -1, ...
            +1, -1, ...
            +1, -1, ...
            +1, +1, ...
            -1, +1, ...
            -1, +1, ...
            -1, -1, ...
            +1, -1, ...
            +1, -1, ...
            +1, +1, ...
            -1]; %  phase current to slot mapping
% 18N22P = ABbcaABCcabBCAabcC

g.s.span = 1; % number of slots spanned by each turn (typically 1 for concentrated winding, 3 for distributed
g.s.turns = 100;

g = calc_geometry(g);
